### ISSUE TITLE
Fullscreen Resolution Bug in Debian Release

### ISSUE THREAD

**Issue by hatchcliff** [atari800/atari800#214] opened 2024-01-04 16:13 UTC
Two related bugs were discovered while testing the v5.2.0 Debian AMD64 release:

- Running at reduced fullscreen resolution, the desktop's original resolution is not restored when atari800 exits, which usually renders the desktop unusable, requiring a reboot.

- The emulator really needs to be run at full monitor resolution because of the above bug, but the menu for setting this crashes.  Changing resolution on the fly seems to be the particular problem.  The workaround is to come out of fullscreen mode, change the resolution, and go back into fullscreen.

Testing was performed with Debian 12 Bookworm and Linux Mint 21.2.
I tried v5.0.0 and 4.2.0, on the same platforms, and they behaved the same, so this does not appear to be connected to recent developments in v5.2.0.
The bugs are not present in the ARMHF and ARM64 v5.2.0 releases, tested on Raspberry Pis.

To reproduce crash:

- Delete or temporarily rename .atari800.cfg, so that the next run imitates the first after installation.
- Run atari800 in a terminal.
- When the small startup window appears press [F1], [Display Settings], [Video mode settings]
- Change [Fullscreen:] to [Yes].
- Change [Fullscreen resolution:] from the default [640x480] to any other setting, [1920x1080] say.

Atari800 crashes giving the following report, and returns to the desktop in 640x480 resolution:

```
cliff@Geekom:~$ atari800
User config file '/home/cliff/.atari800.cfg' not found.
Trying system wide config file: /etc/atari800.cfg
No configuration file found, will create fresh one from scratch:
Writing config file: /home/cliff/.atari800.cfg
Keyboard mapped to emulated joystick 0
Joystick 0 mapped to emulated joystick 0
Requested resolution 336x240 is not available, using 640x480 instead.
Video Mode: 336x240x32 windowed without vsync
Video Mode: 640x480x32 fullscreen without vsync
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  153 (XFree86-VidModeExtension)
  Minor opcode of failed request:  10 (XF86VidModeSwitchToMode)
  Value in failed request:  0x760
  Serial number of failed request:  199
  Current serial number in output stream:  201
cliff@Geekom:~$
```

Making the changes the other way round, choosing the resolution first and switching to fullscreen second, works OK - and this is the basis for the workaround.

**Comment by craigmaloney** [comment] 2024-01-04 16:18
Which video card and what native resolution are you running? My suspicion is that we're tickling an issue with NVidia cards.

**Comment by joysfera** [comment] 2024-01-04 16:49
FYI, the first bug (original resolution is not restored) is probably on all platforms. I encountered it also on Orange Pi PC Plus (armhf).

**Comment by hatchcliff** [comment] 2024-01-04 20:19
My graphics card is an Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics], running at 1920x1080.

I just tried atari800 on my laptop, running the same Linux Mint 21.2 operating system.  Its graphics card is an Intel Corporation Device 3ea1, also running at 1920x1080.  It too fails to restore the desktop resolution on exit, but the symptoms of the other bug are different.  It sometimes changes resolution on the fly successfully, and other times freezes (so I can't see the error report).

It's interesting that failure to restore the desktop resolution affects armhf as well as amd64 systems.  However, the Pi 2 (armhf), and the other Pis (arm64) run fine, so some platforms seem to be unaffected.

**Comment by dmsc** [comment] 2024-01-06 22:52
Hi!

Just tried in my Debian sid setup, compiled from source, just works:

https://github.com/atari800/atari800/assets/5713395/c1058337-f97c-4c89-860c-b416993a7db5


This is the SDL libraries I have installed:
```
$ dpkg -l libsdl1.2*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version      Architecture Description
+++-=====================-============-============-========================================================
ii  libsdl1.2-dev:amd64   1.2.68-2     amd64        SDL 1.2 binary compatibility library - development files
ii  libsdl1.2debian:amd64 1.2.68-2     amd64        SDL 1.2 binary compatibility library wrapping SDL 2.0
```

@hatchcliff , what version of SDL libraries you have installed? Can you post the result of `ldd atari800` ?

Have Fun!

**Comment by hatchcliff** [comment] 2024-01-07 20:57
@dmsc thank you for this!

I am running Debian 12 Bookworm which includes libsdl1.2debian 1.2.15+dfsg2-8 as standard.  You are running a newer version, 1.2.68-2 in Debian Sid.

I downloaded 1.2.68-2, installed it on Debian 12 and both bugs disappeared.

So it appears that the bugs have been fixed, and we just need to wait for 1.2.68-2 to make its way through the approval process into the stable release of Debian.

One remaining puzzle is that the Raspberry Pis don't exhibit the bugs, yet they have the older 1.2.15+dfsg2-8 installed.  So perhaps there are additional factors, such as specific hardware.

Here is the SDL library listed on the faulty system:
```
cliff@Geekom:~$ dpkg -l libsdl1.2* | grep ii
ii  libsdl1.2debian:amd64      1.2.15+dfsg2-8 amd64        Simple DirectMedia Layer
```
and here is the new version on the repaired system (matching your list, except that libsdl1.2-dev is not present because I did not recompile atari800, so did not need it):
```
cliff@Geekom:~$ dpkg -l libsdl1.2* | grep ii
ii  libsdl1.2debian:amd64 1.2.68-2     amd64        SDL 1.2 binary compatibility library wrapping SDL 2.0
```

**Comment by dmsc** [comment] 2024-01-08 16:24
Hi @hatchcliff 

Instead of upgrading SDL to the last unstable version, you could try installing the package `libsdl1.2-compat-shim` , this provides the compatibility to run SDL 1.2 applications via the SDL 2.0 library.

If this works, then the culprit should be the old SDL-1.2 library - the version on Debian simply calls SDL 1.2, as the old package was dropped after the last release.

Even so, I used SDL for a long time without any problems, so surely there is an underlying problem in your setup that introduces some incompatibilities.

- Do you run X or Wayland?
- What window-manager (X) or compositor (wayland)?
- What desktop environment?

Thank you!

**Comment by hatchcliff** [comment] 2024-01-10 16:21
Hi @dmsc

> the newer version on Debian simply calls SDL 1.2

Did you mean "the new version on Debian simply calls SDL 2.0"?  The [documentation on the new version](https://packages.debian.org/sid/libsdl1.2debian) says:

> Package: libsdl1.2debian (1.2.68-2)
> 
> SDL 1.2 binary compatibility library wrapping SDL 2.0
> 
> This package contains sdl12-compat, a binary compatible API for programs built against SDL 1.2, but using SDL 2.0.
> 
> This package replaces the classic SDL 1.2 library with the SDL 2.0 compatibility layer, so that all SDL 1.2 program will use it.
> 
> If you are writing new code, please target SDL 2.0 directly instead of using this layer.

So it's a wrapper for SDL 2.0 containing sdl12-compat.  Given that it works correctly, I think there is little doubt that the bugs are associated with the old SDL 1.2 library libsdl1.2debian 1.2.15+dfsg2-8.

> Even so, I used SDL for a long time without any problems, so surely there is an underlying problem in your setup that introduces some incompatibilities.

I agree.  I tried atari800 v4.2.0 (released in 2019) and found the same bugs.  Petr says that the first one has been around for a long time, but it is hard to imagine the second, which crashes atari800, going unnoticed for 4 years.  The machines I'm using are quite new.  My guess is that we are seeing incompatibilities with modern hardware and drivers, but that this has more to do with SDL 1.2 falling behind than bugs or setup errors in the modern machines.  The fact that SDL 2.0 eliminates the bugs seems to support this.

To answer your questions:

I have both Debian 12 (Wayland) and Linux Mint 21.2 (X) installed.  Both exhibit the bugs and respond to the same fix.  Both run the Cinnamon desktop environment.

**Comment by dmsc** [comment] 2024-01-10 19:25
Hi!

> Hi @dmsc
> 
> > the newer version on Debian simply calls SDL 1.2
> 
> Did you mean "the new version on Debian simply calls SDL 2.0"? The [documentation on the new version](https://packages.debian.org/sid/libsdl1.2debian) says:
> 

Yes, sorry, it was a typo.

> So it's a wrapper for SDL 2.0 containing sdl12-compat. Given that it works correctly, I think there is little doubt that the bugs are associated with the old SDL 1.2 library libsdl1.2debian 1.2.15+dfsg2-8.
> 
> > Even so, I used SDL for a long time without any problems, so surely there is an underlying problem in your setup that introduces some incompatibilities.
> 
> I agree. I tried atari800 v4.2.0 (released in 2019) and found the same bugs. Petr says that the first one has been around for a long time, but it is hard to imagine the second, which crashes atari800, going unnoticed for 4 years. The machines I'm using are quite new. My guess is that we are seeing incompatibilities with modern hardware and drivers, but that this has more to do with SDL 1.2 falling behind than bugs or setup errors in the modern machines. The fact that SDL 2.0 eliminates the bugs seems to support this.
>

Yes, I agree.
 
> To answer your questions:
> 
> I have both Debian 12 (Wayland) and Linux Mint 21.2 (X) installed. Both exhibit the bugs and respond to the same fix. Both run the Cinnamon desktop environment.

Will try to install a VM during the weekend to test this. But there are no bug reports in the Debian bug tracker about this.

Have Fun!

**Comment by mikrosk** [comment] 2024-04-19 23:42
I thought I'll try it on Atari (Falcon) which still uses SDL1.2 (as there is no SDL2 available) but I wasn't able to reproduce this either.

So it seems to be Linux/x86 specific SDL-1.2 bug, closing.

**Closed by mikrosk** 2024-04-19 23:42 UTC
