### ISSUE TITLE
CTRL Key not working on macOS (MacPorts and Brew)

### ISSUE THREAD

**Issue by krischik** [atari800/atari800#177] opened 2022-12-27 10:33 UTC
The CTRL key is not working macOS. This is the case for both the MacPorts as well as the Brew distribution.

# Reproduce

Start emulator into Atari-Basic. Type:

```
10 PRINT "[CTRL]Q[CTRL]W[CTRL]E[CTRL]R[CTRL]T[CTRL]Z"
RUN
```

(I have a german keyboard, hence the `[CTRL]Z` instead of `[CTRL]Y`)

# Expected:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/685853/209652885-11a4745d-6205-4e1d-8bd2-6b7b954f4c14.png">

# Observed:

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/685853/209653258-e61621f2-f08d-4c26-9447-548e4ab4e05d.png">

# Hint:

The **atari800** version from @atarimacosx works correctly. AFAIK @atarimacosx uses SDL Library 2.0 and Metal API and is based **atari800** Version 4.2.

**Comment by atarixle** [comment] 2023-05-11 07:10
What version of Mac OS X / OS X / macOS are you running?
May be it has to do with SDL1. SDL1 is not working well anymore on equal / anything higher than High Sierra. This is where sound issues in Atari800MacX started (I heard this from Mac owners who had these OSses in use, while I mad the jump from 10.7 to 10.11, and then to 10.14, 11, 12 on patched Macs).
When I built Atari800 5.0.0 myself on 10.4, 10.5, 10.6, 10.7, 10.8, and 10.11, I didn't observe this issue, these systems fully support SDL1.

**Comment by krischik** [comment] 2023-05-11 11:50
The bug is from December. Before I answer let me update both Brew and MacPorts and check if the bug still exists.

**Comment by dmsc** [comment] 2023-09-19 15:42
Please, test the patch attached - I also experienced this bug when Debian switched from SDL1 to SDL12-COMPAT.

[001-fixes-keyboard-with-sdl12-compat.txt](https://github.com/atari800/atari800/files/12663393/001-fixes-keyboard-with-sdl12-compat.txt)

This is also in a branch in my repo: https://github.com/dmsc/atari800/commit/4e02766fb9ac05d98449f8cb3cfb5731c66524ca

**Comment by jhusak** [comment] 2023-11-21 08:58
The patch worked on Ventura/M1. Thank you.

**Comment by joysfera** [comment] 2023-11-21 09:21
@dmsc would you create a pull request with the keyboard fixes? Has it been tested on more platforms yet?

**Comment by dmsc** [comment] 2023-11-21 15:32
Hi!

It works on current Debian Unstable, and it works for @jhusak .

The problem is I don't know if it works in older versions of SDL.

@joysfera ¿does it work for you?

Have Fun!

**Comment by jhusak** [comment] 2023-11-21 17:16
I have compiled atari800 from sources with patch applied on MacBookPro Intel with Mojave and it works with control and shift and so. Capslock works too in the same manner. In other words - for me no difference on older mac with patch or without.

**Comment by krischik** [comment] 2023-11-22 06:37
Sadly there is no new release which means I can't update MacPorts (yes, I'm the MacPorts maintainer). It's also unlikely the the Homebrew maintainer will update without an official release.

Considering that is also affects Debian: what are the chances of an 5.0.1 release any time soon? Alternatively I could patch it in for MacPorts as a hotfix but I prefer a proper release.

**Comment by mikrosk** [comment] 2024-05-08 13:34
This was fun. While investigating #206, I have realised that this was the wrong way to fix the CAPSLOCK issue. It should have been reported in the sdl12-compat project (as have done now) since it is their bug, not ours.

Anyway, since we don't want to have broken Atari800 release, I have put the CAPSLOCK code into an `#if` so it works in both native SDL 1.2 and SDL12-compat.

@dmsc I have "reverted" only the "ugly hack" part, the rest seems to be work on native SDL 1.2, too. Just to be on the safe side, does the change in 1a50481 looks OK to you (if it runs on the "broken" SDL 1.2 and not SDL12-compat).

**Comment by mikrosk** [comment] 2024-05-11 18:41
@krischik can you please verify that the CAPSLOCK issue has been fixed for you in 5.2.0? We have a user report about 5.2.0 where the CAPSLOCK key still doesn't work on Macs: https://sourceforge.net/p/atari800/mailman/message/58770622 (it doesn on Linux).

**Comment by dmsc** [comment] 2024-05-12 01:37
Hi!

Sorry for not replying earlier.

> This was fun. While investigating #206, I have realised that this was the wrong way to fix the CAPSLOCK issue. It should have been reported in the sdl12-compat project (as I have done now) since it is their bug, not ours.
> 
> Anyway, since we don't want to have broken Atari800 release, I have put the CAPSLOCK code into an `#if` so it works in both native SDL 1.2 and SDL12-compat.
> 
> @dmsc I have "reverted" only the "ugly hack" part, the rest seems to be work on native SDL 1.2, too. Just to be on the safe side, does the change in [1a50481](https://github.com/atari800/atari800/commit/1a5048125062f1ec7ddbb4f6fb81465fc431ce60) looks OK to you (if it runs on the "broken" SDL 1.2 and not SDL12-compat).

It seems OK.

Problem with the Atari800 code is that it supported too many semi-incompatible platforms, so it was littered with small "ugly fixes" that now don't make much sense.

On a related note, I recently added a github action to my fastbasic repo to compile and test in Linux, Windows and MacOS. this could be added here so you could point the users to download and test the binary easily.

Have Fun!

**Comment by mikrosk** [comment] 2024-05-12 06:17
@dmsc I agree, having binary snapshots is useful. Where do you store the files, though? In the past I used bintray.com and since they cancelled the free plans, private hosting with ash keys stored as secret. But that's not optimal, as we depend on the person providing the storage.

**Comment by mikrosk** [comment] 2024-05-12 06:22
Steve reported that recent fixes also fixed the capslock issue, so closing again. But confirmation from another Mac user is still welcome.

**Closed by mikrosk** 2024-05-12 06:22 UTC

**Comment by dmsc** [comment] 2024-05-12 23:35
Hi!

> @dmsc I agree, having binary snapshots is useful. Where do you store the files, though? In the past I used bintray.com and since they cancelled the free plans, private hosting with ash keys stored as secret. But that's not optimal, as we depend on the person providing the storage.

They are stored in github ar "build artifacts". I created pull request #232 and it seems to work.

Have Fun!

**Comment by dmsc** [comment] 2024-05-12 23:37
See a test here: https://github.com/dmsc/atari800/actions/runs/9054996227
The downloadable file is at the bottom:
![image](https://github.com/atari800/atari800/assets/5713395/6b2aec21-59ac-4db9-800c-8bb0df8ab7f9)
