### ISSUE TITLE
Caps key inoperative

### ISSUE THREAD

**Issue by CJeUv** [atari800/atari800#234] opened 2024-06-23 22:53 UTC
Just bumped the Caps key while editing a Basic program.  There was a single key click followed by continuous repeating key clicks until I pressed Caps again.  Then there were NO key clicks for other keys for a few keys then seemed ok until I pressed Shift then clicks off again.  All keyboard activity was strange and unpredictable.  I then entered UI and all was ok, pressed Caps and no clicks but keyboard indicated Caps had been pressed. I exited Atari800 and tried Text Editor, Caps and Shift worked normally.  I then shutdown to try another keyboard and still the same Caps issue as before.  I also switched to the original installed Atari800 and has the same Caps issue.  If the basic program is running then there are NO key clicks and the Caps/Shift seems to work correctly after basic is stopped.  I tried a game loader called MyPicoDos and the Caps issue repeats but after pressing Caps to stop the clicks the keyboard joy stick to move the cursor was inactive but started working again after being Reset.

**Comment by mikrosk** [comment] 2024-06-24 07:17
As I have worked on several CAPSLOCK issues, I'm quite surprised to hear this. Can you please provide:

- what version did you try?
- what platform?
- if applicable, which SDL version is installed in your system?

**Comment by CJeUv** [comment] 2024-06-24 14:45
Current Version 5-2-0
Raspberry Pi 3B running Raspberry Pi Bookworm up to date
SDL is part of Atari800 5-2-0

**Comment by mikrosk** [comment] 2024-06-24 18:39
SDL is not "part of Atari800", it's installed in your system. Can you please run `dpkg -l | grep -i sdl` and post the output?

I presume you installed Atari800 from the repository `apt install atari800` and not compiled by yourself?

**Comment by CJeUv** [comment] 2024-06-24 22:09
CJeUv@raspberrypi:~ $ dpkg -l | grep -i sdl
ii  atari800:armhf                        5.2.0                               armhf        Atari 8-bit emulator for SDL
ii  libsdl-image1.2:arm64                 1.2.12-13+b2                        arm64        Image loading library for Simple DirectMedia Layer 1.2, libraries
ii  libsdl1.2-dev                         1.2.15+dfsg2-8                      arm64        Simple DirectMedia Layer development files
ii  libsdl1.2debian:arm64                 1.2.15+dfsg2-8                      arm64        Simple DirectMedia Layer
ii  libsdl1.2debian:armhf                 1.2.15+dfsg2-8                      armhf        Simple DirectMedia Layer
ii  libsdl2-2.0-0:arm64                   2.26.5+dfsg-1                       arm64        Simple DirectMedia Layer
ii  libsdl2-image-2.0-0:arm64             2.6.3+dfsg-1                        arm64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-mixer-2.0-0:arm64             2.6.2+dfsg-2                        arm64        Mixer library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-2.0-0:arm64               2.20.1+dfsg-2                       arm64        TrueType Font library for Simple DirectMedia Layer 2, libraries
ii  python3-pygame                        2.1.2+dfsg-5+b1                     arm64        SDL bindings for games development (Python 3)
CJeUv@raspberrypi:~ $

**Comment by mikrosk** [comment] 2024-06-25 06:33
You didn't answer my other question, whether it is the version supplied by your packager or whether did you compile it by yourself.

As nobody else has reported this, it is either a bug with the RPi build (but I guess @hatchcliff would notice?) or something in your setup because I can't reproduce this on three other platforms (Windows, Linux, Atari Falcon).

**Comment by hatchcliff** [comment] 2024-06-26 15:42
I just tried this on my Pi3 and AMD64 machines and found the same problem on both.
It looks like a bug in the v5.2.0 packages available from the [Releases Area](https://github.com/atari800/atari800/releases) to me.
I tried compiling and running the development version on GitHub, and it behaved normally - so it seems the problem has already been fixed.
I also tried v5.0.0 (the latest version available from the Debian Project) and it too behaved normally.
I used the Atari 800 built in keyboard test to identify the bug.  If pressing and releasing **caps lock** produces a continuous beep, the bug is present.  If the beep persists only for as long as the key is held down, this is normal.
On original Atari hardware, I believe **caps** switched to lower case and **shift+caps** switched back to upper case (I don't have my machine out at present to check this).  I assume that on the emulator **caps lock** should simply toggle upper and lower case modes - is this correct?

**Comment by mikrosk** [comment] 2024-06-26 17:10
> On original Atari hardware I believe caps switched to lower case and shift+caps switched back to upper case (I don't have my machine out at present to check this). I assume that on the emulator caps lock should simply toggle upper and lower case modes - is this correct?

On Atari:
- plain caps lock toggles between lowercase and uppercase
- holding caps lock makes a continous beep sound (and toggling)
- shift+caps lock activates uppercase (no toggle)
- holding shift+caps lock makes a continous beep sound (and toggling)
- control+caps lock actives the graphics charset
- plain caps lock after control+caps lock switches back to lowercase
- shift+caps lock after control+caps lock switches back to uppercase

I have verified that this behaviour is faithfully reproduced in latest master.

@hatchcliff does it behave differently for you?

**Comment by hatchcliff** [comment] 2024-06-26 18:58
The latest master works the same for me except the following don't produce a continuous beep, just a normal keyclick.  The action is same as a normal keystroke, regardless of how long the keys are held down.
- holding caps lock makes a continous beep sound (and toggling)
- holding shift+caps lock makes a continous beep sound (no toggling)

I don't think this difference is significant.  All the actions seem sensible to me as they are.  I don't see anything that needs fixing for future releases, so I think we can probably close this issue.

However, the functionality is not the same in v5.2.0, particularly with regard to the **caps lock** key, and I assume this explains why the issue was raised.

**Comment by mikrosk** [comment] 2024-06-26 19:51
Hmm, aren't you by any chance using the original libSDL-1.2 on your RPi, are you? Because quite recently I have reported this bug: https://github.com/libsdl-org/sdl12-compat/issues/331. Basically, when using libsdl12-compat, you _do_ get multiple key down/key up events and therefore the caps lock works as intended (i.e. producing multiple beeps). However on the original libsdl-1.2, there is no way to produce result like that, so what we do is to just accepting one beep and that's it:https://github.com/atari800/atari800/blob/2c80502fb7724ea0936e8879d6f457a2bf58e64a/src/sdl/input.c#L440-L450.

I have verified this behaviour also on Atari Falcon (libsdl-1.2) port.

**Comment by hatchcliff** [comment] 2024-06-27 15:38
Thanks @mikrosk, that explains a lot.

> Hmm, aren't you by any chance using the original libSDL-1.2 on your RPi, are you?

I'm using the [current Bookworm version 1.2.15](https://packages.debian.org/stable/libs/libsdl1.2debian), the same as CJeUv.

I tried substituting [Sid version 1.2.68](https://packages.debian.org/sid/libsdl1.2debian) (which is a wrapper for SDL2) and the bug in v5.2.0 disappeared.

Incidentally, I saw the same behaviour on my AMD64 machine running Debian and Mint, so this is probably an issue for all Debian based systems - not just the Raspberry Pi.

The problem may already be fixed for future releases, but I think it is a genuine issue for v5.2.0 users running the standard version of libSDL-1.2 - probably the majority of users because this is the default position.

@CJeUv, until the next release, one workaround available to you is to revert to Atari800 v5.0.0, which you can obtain from the [Releases Area](https://github.com/atari800/atari800/releases).  You will lose some updates of course, so this is not ideal.

Installing an SDL2 wrapper overloads the Pi3, so is not an option unless you are able to migrate to a more powerful machine, a Pi4 or 5 for example.

**Comment by mikrosk** [comment] 2024-06-27 17:35
Oh, I see. I had no idea there are still distros with native libSDL-1.2. 

Just to be sure, when you say:

>I tried compiling and running the development version on GitHub, and it behaved normally - so it seems the problem has already been fixed.
>I also tried v5.0.0 (the latest version available from the Debian Project) and it too behaved normally.

by "normally" you mean single key click on CAPSLOCK hold, right? If so, then all is clear, there is no mystery anymore: the #177 side effect applies also to you, not only Atari Falcon SDL backend.

**Comment by hatchcliff** [comment] 2024-06-28 14:45
> by "normally" you mean single key click on CAPSLOCK hold, right?

Yes, that's right.

With both v5.0.0 and the current master (running with Bookworm libsdl1.2debian version 1.2.15) holding down **caps lock** produces a single click and toggles upper/lower case correctly.

**Comment by mikrosk** [comment] 2024-06-28 16:16
Happy to close then.

**Closed by mikrosk** 2024-06-28 16:16 UTC
