### ISSUE TITLE
"Bounty Bob Strikes Back" cart version doesn't recognize the space bar

### ISSUE THREAD

**Issue by Shamus397** [atari800/atari800#33] opened 2018-06-08 22:40 UTC
This is with the latest version in the git repo and has been an issue for a long time now, going back to v3.1.0 and before. For some reason, the cartridge version of "Bounty Bob Strikes Back" doesn't react when the space bar is pressed on level 2. Also, the lift does not activate when you jump on it either (which it should). Using "1" and "2" on the keyboard to activate the transporters works as it should, so it's not ignoring all keys. This is on an XL NTSC emulated system, using a USB gamepad for input; host system is Linux/SDL.

I also verified that all works normally with the tape version (XL/PAL), so it's just the cart version that has this issue.

**Comment by mikrosk** [comment] 2019-06-18 09:04
@Shamus397 can you try to reproduce without the gamepad, using keyboard -> joystick emulation only?

**Comment by mikrosk** [comment] 2019-06-18 12:45
@ChoccyHobNob as you are the local BBSB expert ;), can you confirm this?

**Comment by ChoccyHobNob** [comment] 2019-06-18 13:07
Sure I’ll give BBSB a good going over today (it’s only 8am here) and let you know about stereo and the space bar

**Comment by ChoccyHobNob** [comment] 2019-06-18 19:31
OK So, The BBSB works in real hardware even if Stereo POKEYs are installed. I tried multiple versions all of them were fine.

The space bar thing is a different issue to what is being reported. The game has a Utility Hoist (First time you use it is level 2) when you land on the hoist you stick to it, the joystick moves the hoist around, you press space to stop it to get off or press space again to re-stick to it. 

In Atari800 if you land on the hoist it doesn’t get activated at all so you can’t control it. 

This is true for all versions except for the USGold cassette version which works fine and the Homesoft XEX version which is also OK.

Obviously this all works fine on real hardware, also works in Altirra.

There is discussion about it on AtariAge back to 2010 so it’s been a known thing with this emulator for a long time.

There is another issue with BBSB in that it doesn’t work (the joystick is non-responsive) if you have a U1MB installed (The Homesoft XEX is fixed to work, none of the other versions are controllable at all. That made testing all this on real hardware a royal pain as my 1088XEL has a U1MB.

**Comment by joysfera** [comment] 2019-06-18 19:35
so all we need is to point users to Homesoft XEX version and we're good?

**Comment by ChoccyHobNob** [comment] 2019-06-18 19:37
ಠ_ಠ

**Comment by Shamus397** [comment] 2019-06-19 02:28
Yes, it displays the exact same behavior using the built-in emulated (keyboard) joystick.  As an aside, at some point I seem to remember this being fixed but I can't for the life of me remember which version it was (I could also be misremembering that, as it was a quite a few years ago).  FWIW.

**Comment by mikrosk** [comment] 2019-06-19 05:47
> Obviously this all works fine on real hardware, also works in Altirra.

Does this apply also for the stereo bug? Because the original thread mentioned in #10 says that it doesn't work in Altirra and works on real hardware only by chance.

**Comment by ChoccyHobNob** [comment] 2019-06-19 12:14
The stereo bug is also a problem in Altirra. 

I couldn’t get it to fail at all yesterday in real hardware using multiple carts, multiple times.

**Comment by joysfera** [comment] 2019-06-19 13:37
Another option is to turn off the stereo POKEY support and also extended memory support and let every user enable it on their own, if I understand the stereo POKEY issue correctly. Would that fix some of the BBSB issues? And would it be worth it?

**Comment by ChoccyHobNob** [comment] 2019-06-19 14:04
Yes, by default atari800 should emulate a standard Atari, if a user wants to add a stereo POKEY or more memory, that is a decision they should make for themselves.

A while ago I brought up that there is no command line switch to enable/disable stereo (or memory over 128K) I found a workaround using multiple config files and you closed the issue but really those options _should_ have a command line switch, especially if you are making the decision to disable it by default…

**Comment by Shamus397** [comment] 2019-06-19 18:30
This problem is unrelated to the stereo pokey option; also, I had stereo pokey disabled (I never have that option enabled).  I feel I should also add that this was on an emulated stock XL with no extras enabled either (no extra memory, no patches, etc).  So whatever the issue is, it's probably in the core of the emulation.

**Comment by mikrosk** [comment] 2019-06-19 19:08
Sure, I was just asking to make sure that Altirra somehow magically hasn't started working with the stereo bug (as it is reportedly working with this space bar bug).

@ChoccyHobNob can you point me to the AtariAge thread discussing this (space bar) bug? Just in case, whether it doesn't provide some leads what's wrong.

**Comment by ChoccyHobNob** [comment] 2019-06-19 19:35
Yeah there is a bug in atari800 which causes the lift not to activate in BBSB.

**Comment by ChoccyHobNob** [comment] 2019-06-19 19:37
It doesn’t provide any leads, just Kr0tki telling everyone to use a better emulator

https://atariage.com/forums/topic/167524-how-do-i-work-the-utility-hoist-in-bounty-bob-strikes-back/

**Comment by joysfera** [comment] 2019-06-19 20:13
This video should get even those who don't remember the game on the same page:
https://youtu.be/18n-MBlVIvw?t=172
:-)

**Comment by mikrosk** [comment] 2020-01-05 13:37
I confirm the issue. Since I spent half an hour to get into level two, I'm attaching a saved state for debugging purposes. Use it as `atari800 -state bbsb.sav`.

It would really help if somebody could provide a disassembled code snapshot (maybe someone from the AA experts?) so we would know how the check look like.

[bbsb.sav.zip](https://github.com/atari800/atari800/files/4023423/bbsb.sav.zip)

**Comment by kr0tki** [comment] 2020-11-30 20:41
Closing - fixed by PR #123.

**Closed by kr0tki** 2020-11-30 20:41 UTC
