### ISSUE TITLE
Add support for N: device like Fujinet

### ISSUE THREAD

**Issue by ericpareja** [atari800/atari800#154] opened 2021-11-14 14:50 UTC
Similar to the R: device, except it emulates the N: device provided by Fujinet.

**Comment by ericpareja** [comment] 2022-02-02 12:10
See https://github.com/FujiNetWIFI/fujinet-emulator-bridge

**Comment by mikrosk** [comment] 2023-11-23 12:53
Duplicate of #127 (despite of its misleading name).

**Closed by mikrosk** 2023-11-23 12:53 UTC
Labels: enhancement
