### ISSUE TITLE
High CPU usage in monitor?

### ISSUE THREAD

**Issue by SasQ** [atari800/atari800#97] opened 2020-04-13 00:52 UTC
I run atari800 (v. 3.1.0-r1 on Gentoo Linux), then go to the Monitor by hitting F8, the simulation is **paused** and one might expect that it should not grind the CPU too much, right? :q 

And yet, after a couple of minutes, it **starts using 70..100% CPU** despite that I'm doing nothing in the Monitor and the simulation is paused (the simulation window disappeared).

I attached GDB to it to check what function does it run. There seems to be three threads, one of them being the main thread. The main thread doesn't seem to do much, just waiting for user input in `readline` routine:

  main → Atari800_Frame → UI_Run → Atari800_Exit → PLATFORM_Exit → MONITOR_Run → safe_gets → {1 readline → readline_internal_char→ rl_read_key → rl_getc → {0 pselect } }

(I marked library boundaries with numbered braces: 0=libc, 1=libreadline, 2=libpthread, 3=libSDL-1.2, 4=libpulse, 5=libpulsecommon, 6=libasound, 7=libasound_module_pcm_pulse.)

The other two threads call some stuff from `libSDL` and `PulseAudio`:

{0 clone → {2 start_thread → {5 ? → {4 ? → pa_mainloop_run → pa_mainloop_iterate → pa_mainloop_poll → {0 poll} } }

{0 clone → {2 start_thread → {3 ? → ? → ? → ? → {6 ? → ? → ? → ? → {7 ? → ? → {4 pa_stream_writable_size → {5 pa_detect_fork → {0 getpid} } } } } } } }
so my guess is that there is a problem with some callbacks from the sound API racing with each other. Another hint that this might be the case is that I sometimes get the following message on the terminal:

ALSA lib /{...redacted...}/alsa-lib-1.1.2/src/pcm/pcm.c:8251:(snd_pcm_recover) underrun occurred

and the CPU usage seems to raise a while after the first of these messages appear.

**Comment by mikrosk** [comment] 2020-04-13 07:55
Can you reproduce this with the latest version, too?

**Comment by SasQ** [comment] 2020-04-13 21:09
Yes, the one from the master branch does that too. Same exact behaviour.

**Comment by kr0tki** [comment] 2020-11-29 05:57
I cannot reproduce it on Kubuntu 20.10. I have run Atari800, then after a few seconds pressed F8 and left it like that for 30 minutes. pulseaudio kept taking 1-2% of CPU time, but at no time it jumped above that; and atari800 was completely inactive. (I could not reproduce the issue on Windows, either.)

@SasQ could you answer these questions?
1. What time does it take for the CPU usage to kick in? Is that time more or less constant?
2. What version of SDL, pulseaudio and ALSA do you use? What processor architecture do you have there? (In my case it's 1.2.15, 13.99.2, 1.0.25, and x86_64, respectively.)
3. Was Atari800 in fullscreen mode when you pressed F8? Does it change anything if it is/isn't fullscreen?
4. Does the issue repeat even if you turn the PulseAudio daemon off and audio is passed directly to ALSA? ([Here](https://learn.foundry.com/nuke/content/timeline_environment/managetimelines/audio_pulse.html) are instructions on stopping/starting PulseAudio for a while.)
5. What desktop environment are you using? Can you test if the issue persists under another DE?
6. Does the issue repeat when you first go F1 to main menu and then select "Enter Monitor" from the menu?
7. Does the issue repeat when you simply go F1 to main menu and then wait?
8. Does the issue repeat when you run atari800 with the "-monitor" command line parameter and then wait?

On my system, gdb only shows two threads for some reason: the main Atari800 one and the second that gets to pa_mainloop_poll.

When Atari800 starts monitor, it closes the SDL video subsystem, but only pauses the audio subsystem. (See src/sdl/main.c -> PLATFORM_Exit.) This leaves the SDL audio output open, but stops the SDL audio callback. Maybe the issue is that on some systems it is not allowed to have the SDL audio output open while the video subsystem is disabled?

I have made an attempt in the "issue97" branch to fix this issue. SasQ, could you test that branch for me?

**Comment by mikrosk** [comment] 2023-11-23 13:35
Closing as fixed as @kr0tki's commit made it to master after all.

**Comment by mikrosk** [comment] 2024-04-20 18:03
Hold on. Now I see that @kr0tki's commit was pushed into https://github.com/atari800/atari800/tree/issue97, not into master so reopening.

**Closed** 2024-04-20 22:58 UTC
